# Generated by Django 4.1 on 2023-05-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_general', '0004_coupon_for_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='type',
        ),
    ]
