# Generated by Django 4.1 on 2023-05-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_general', '0004_coupon_for_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_images', to='api_general.city')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_images', to='api_general.image')),
            ],
            options={
                'db_table': 'city_images',
            },
        ),
    ]
