# Generated by Django 4.1 on 2023-05-16 16:18

from django.db import migrations

from api_general.statics import data


def initial_city_img_data(apps, schema_editor):
    city_model = apps.get_model("api_general", "City")
    image_model = apps.get_model("api_general", "Image")
    city_image_model = apps.get_model("api_general", "CityImage")

    cities = city_model.objects.all().order_by("id")
    cities_image_data = data
    image_cities = []
    for idx, city in enumerate(cities, 1):
        image = image_model(link=cities_image_data[str(idx)])
        image.save()

        image_cities.append(city_image_model(image=image, city=city))

    city_image_model.objects.bulk_create(image_cities)


def delete_all_data(apps, schema_editor):
    city_image_model = apps.get_model("api_general", "CityImage")
    city_image_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api_general', '0005_cityimage'),
    ]

    operations = [
        migrations.RunPython(initial_city_img_data, delete_all_data)
    ]
