# Generated by Django 4.1 on 2023-05-17 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_general', '0005_remove_coupon_type'),
        ('api_general', '0006_migrate_citi_image'),
    ]

    operations = [
    ]
