# Generated by Django 4.1 on 2023-06-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_general', '0007_merge_0005_remove_coupon_type_0006_migrate_citi_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='for_all',
            field=models.BooleanField(default=False),
        ),
    ]
