# Generated by Django 4.1 on 2023-04-23 16:19

from django.db import migrations
from craw_data.craw_city import get_data_for_city


def initial_city_data(apps, schema_editor):
    city_model = apps.get_model("api_tour", "City")

    cities = []

    for city in get_data_for_city():
        cities.append(city_model(id=city[0], name=city[1],
                                 zipcode=city[2], country='Việt Nam'))

    city_model.objects.bulk_create(cities)


def delete_all_data(apps, schema_editor):
    city_model = apps.get_model("api_tour", "City")
    city_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api_tour', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_city_data, delete_all_data)
    ]
