# Generated by Django 4.1 on 2023-04-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tour', '0002_migrate_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
