# Generated by Django 4.1 on 2023-05-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tour', '0002_migrate_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='departure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='traffics',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
