# Generated by Django 4.1 on 2023-04-28 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('api_tour', '0003_alter_tour_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.image'),
        ),
    ]
