# Generated by Django 4.1 on 2023-04-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tour', '0003_tour_latitude_tour_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='language_tour',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='total_days',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
