# Generated by Django 4.1 on 2023-04-28 03:58
import random

from django.db import migrations
import json

from api_user.statics import RoleData


def initial_tour_data(apps, schema_editor):
    city_model = apps.get_model("api_tour", "City")
    tour_model = apps.get_model("api_tour", "Tour")
    image_model = apps.get_model("base", "Image")
    tour_image_model = apps.get_model("api_tour", "TourImage")
    profile_models = apps.get_model("api_user", 'Profile')
    role_model = apps.get_model("api_user", "Role")
    partner_role = role_model.objects.filter(id=RoleData.PARTNER.value.get('id')).first()
    partner = profile_models.objects.filter(role=partner_role)

    with open('api_tour/statics/craw_datatour_data.txt', 'r', encoding='utf-8') as f:
        list_data = json.load(f)

    for data in list_data:
        city = city_model.objects.filter(name=data['city']).first()

        try:
            price = int(data['price'].replace(",", "").replace("đ", ""))
        except Exception:
            price = 3000000
        tour = tour_model(
            name=data['name'], cover_picture=data['cover_image'],
            city=city, descriptions=data['description'],
            schedule_content=data['schedule_content'], note=data['note'],
            num_review=int(data['num_review']), group_size=data['group_size'],
            price=price, owner=partner[random.randint(0, len(partner)-1)],
            total_days=data['total_days'], language_tour="Việt Nam"
        )
        tour.save()
        tour = tour_model.objects.filter(name=data['name']).first()
        tour_images = []
        for link in data['images']:
            image = image_model(link=link)
            image.save()
            image = image_model.objects.filter(link=link).first()
            tour_images.append(tour_image_model(image=image, tour=tour))
        tour_image_model.objects.bulk_create(tour_images)


def delete_all_data(apps, schema_editor):
    tour_model = apps.get_model("api_tour", "Tour")
    image_model = apps.get_model("base", "Image")
    tour_image_model = apps.get_model("api_tour", "TourImage")
    tour_model.objects.all().delete()
    image_model.objects.all().delete()
    tour_image_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api_tour', '0004_alter_tourimage_image'),
    ]

    operations = [
        migrations.RunPython(initial_tour_data, delete_all_data)
    ]
