# Generated by Django 4.1 on 2023-05-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tour', '0005_tourcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='total_days',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
