# Generated by Django 4.1 on 2023-05-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_booking', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingitem',
            old_name='quality',
            new_name='quantity',
        ),
    ]
