# Generated by Django 4.1 on 2023-05-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_booking', '0003_rename_quality_bookingitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bank_code',
            field=models.CharField(blank=True, choices=[('NCB', 'Ncb'), ('VISA', 'Visa'), ('MasterCard', 'Master Card'), ('JCB', 'Jcb')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
