# Generated by Django 4.1 on 2023-05-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_booking', '0004_booking_bank_code_alter_bookingitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='history_discount_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='history_origin_price',
            field=models.FloatField(null=True),
        ),
    ]
