# Generated by Django 4.1 on 2023-05-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_booking', '0005_booking_history_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.IntegerField(choices=[(1, 'Hotel'), (2, 'Tour')], default=1),
        ),
    ]
