# Generated by Django 4.1 on 2023-06-19 14:27

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_hotel', '0012_room_benefit'),
        ('api_tour', '0007_remove_tour_num_review_alter_tour_language_tour'),
        ('api_booking', '0007_bookingreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.IntegerField(choices=[(1, 'Hotel'), (2, 'Tour')], default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_booking', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_hotel.hotel')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_tour.tour')),
            ],
            options={
                'db_table': 'booking_favorites',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
