# Generated by Django 4.1 on 2023-04-13 16:36
import os
import uuid

from django.contrib.auth.hashers import make_password
from django.db import migrations

from api_user.statics.data import ProfileData, RoleData
from dotenv import load_dotenv

load_dotenv()


def initial_profile_data(apps, schema_editor):
    profile_model = apps.get_model("api_user", "Profile")
    role_model = apps.get_model("api_user", "Role")

    admin_role = role_model.objects.filter(id=RoleData.ADMIN.value.get('id')).first()
    partner_role = role_model.objects.filter(id=RoleData.PARTNER.value.get('id')).first()
    customer_role = role_model.objects.filter(id=RoleData.CUSTOMER.value.get('id')).first()

    profiles = []

    for key, items in ProfileData.items():
        new_role = admin_role if key == "admin_account" else (
            partner_role if key == 'partner_account' else customer_role
        )
        for item in items:
            profiles.append(profile_model(id=uuid.uuid4(), email=item['email'],
                            password=make_password(os.getenv('DEFAULT_PASSWORD')),
                            avatar=item['avatar'], role=new_role,
                            last_name=item['last_name'], first_name=item['first_name'],
                            gender=item['gender'], birthday=item['birthday'],
                            address=item['address'], phone=item['phone']))

    profile_model.objects.bulk_create(profiles)


def delete_all_data(apps, schema_editor):
    profile_model = apps.get_model("api_user", "Profile")
    profile_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_migrate_role'),
    ]

    operations = [
        migrations.RunPython(initial_profile_data, delete_all_data)
    ]
