# Generated by Django 4.1 on 2023-06-14 16:05

import base.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0003_migrate_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=base.models.fields.TinyIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=3),
        ),
    ]
