# Generated by Django 4.1 on 2023-05-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active',
        ),
    ]
