# Generated by Django 4.1 on 2023-05-04 16:57
import json
import os
from typing import List

from django.db import migrations

from api_user.models import Profile
from api_user.services import ProfileService

default_cover_image = "https://ik.imagekit.io/tvlk/apr-asset/dgXfoyh24ryQLRcGq00cIdKHRmotrWLNlvG-TxlcLxGkiDwaUSggleJNPRgIHCX6/hotel/asset/20016842-3078abf5cf90a3ec8b59453f05737775.jpeg?_src=imagekit&tr=c-at_max,h-488,q-40,w-768"


def initial_hotel_and_review_data(apps, schema_editor):
    hotel_model = apps.get_model("api_hotel", "Hotel")

    hotel_data_directory = "craw_data/all_hotel_data"
    anonymous_users: List[Profile] = ProfileService.bulk_create_anonymous_users()
    all_files = os.listdir(hotel_data_directory)
    for _file_name in all_files:
        if _file_name.endswith(".json"):
            with open(f"{hotel_data_directory}/{_file_name}", "r", encoding='utf-8') as file:
                file_data: dict = json.loads(file.read())
                hotel_data: dict = file_data.get("hotel", {})
                hotel_images: List[str] = hotel_data.get("images", [])
                cover_picture: str = hotel_images[0] if hotel_images else default_cover_image
                hotel = hotel_model(
                    name=hotel_data.get("name", ""),
                    cover_picture=cover_picture,
                    address=hotel_data.get("location", ""),
                    longitude=hotel_data.get("geo_data", {}).get("longitude", 0),
                    latitude=hotel_data.get("geo_data", {}).get("latitude", 0)
                )


class Migration(migrations.Migration):

    dependencies = [
        ('api_hotel', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_hotel_and_review_data, migrations.RunPython.noop)
    ]
