# Generated by Django 4.1 on 2023-05-07 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_hotel', '0002_roomtype_remove_hotel_group_size_remove_hotel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='beds',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='square',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='hotelreview',
            unique_together={('hotel', 'owner')},
        ),
    ]
