# Generated by Django 4.1 on 2023-05-07 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_hotel', '0003_alter_roomtype_beds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreview',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reviews', to='api_hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelreview',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
