# Generated by Django 4.1 on 2023-05-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_hotel', '0004_alter_hotelreview_hotel_alter_hotelreview_owner'),
        ('api_hotel', '0004_migrate_room_type_room'),
    ]

    operations = [
    ]
