# Generated by Django 4.1 on 2023-05-08 16:51

from django.db import migrations

from utils import read_content
import random


def initial_des_rules_for_hotel(apps, schema_editor):
    hotel_model = apps.get_model("api_hotel", "Hotel")
    hotels = hotel_model.objects.all()
    des_path = 'api_hotel/statics/html/description_hotel'
    rul_path = 'api_hotel/statics/html/rules_hotel'

    for idx, hotel in enumerate(hotels):
        print("Migrate for hotel: ", idx)
        des = des_path + '/des' + str(random.randint(1, 2)) + '.html'
        rul = rul_path + '/rul' + str(random.randint(1, 2)) + '.html'
        description = read_content(des)
        hotel.descriptions = description
        hotel.rules = rul
        hotel.save()
        print("------Done\n")


class Migration(migrations.Migration):

    dependencies = [
        ('api_hotel', '0005_merge_20230507_2232'),
    ]

    operations = [
        migrations.RunPython(initial_des_rules_for_hotel, migrations.RunPython.noop)
    ]
