# Generated by Django 4.1 on 2023-05-11 15:02

from django.db import migrations


def delete_all_data(apps, schema_editor):
    room_type_model = apps.get_model("api_hotel", "RoomType")
    room_model = apps.get_model("api_hotel", "Room")
    room_type_image_model = apps.get_model("api_hotel", "RoomTypeImage")
    room_type_model.objects.all().delete()
    room_model.objects.all().delete()
    room_type_image_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api_hotel', '0007_remove_hotel_num_review_alter_hotelimage_hotel_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_all_data, migrations.RunPython.noop)
    ]
