# Generated by Django 4.1 on 2023-05-11 15:40

from django.db import migrations
import json
import random


def initial_room_data(apps, schema_editor):
    pass
    room_model = apps.get_model("api_hotel", "Room")
    room_image_model = apps.get_model("api_hotel", "RoomImage")
    image_model = apps.get_model("api_general", "Image")
    hotel_model = apps.get_model("api_hotel", "Hotel")
    hotels = hotel_model.objects.all()

    with open('api_hotel/statics/room_type.txt', 'r', encoding='utf-8') as f:
        list_data = json.load(f)

    len_room_type = len(list_data)

    for idx, hotel in enumerate(hotels):
        print("Migrate for hotel: ", idx)
        random_room_types = list_data[str(random.randint(0, len_room_type-1))]

        for room_type in random_room_types:
            room_instance = room_model(name=room_type['name'], beds=room_type['beds'],
                                       adults=int(room_type['adults']), children=int(room_type['children']),
                                       description=room_type['description'], square=room_type['square'],
                                       price=int(room_type['price']), hotel=hotel, quantity=random.randint(5, 10))
            list_room_type_image = []
            room_instance.save()
            for image in room_type['images']:
                image_instance = image_model(link=image)
                image_instance.save()
                room_type_image = room_image_model(image=image_instance, room=room_instance)
                list_room_type_image.append(room_type_image)
            room_image_model.objects.bulk_create(list_room_type_image)
        print("------Done\n")


def delete_all_data(apps, schema_editor):
    room_model = apps.get_model("api_hotel", "Room")
    room_image_model = apps.get_model("api_hotel", "RoomImage")
    room_image_model.objects.all().delete()
    room_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api_hotel', '0009_roomimage_remove_roomtypeimage_image_and_more'),
    ]

    operations = [
        migrations.RunPython(initial_room_data, delete_all_data)
    ]
