# Generated by Django 4.1 on 2023-05-14 03:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_general', '0003_coupon'),
        ('api_hotel', '0010_migrate_data_again'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelCoupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_coupons', to='api_general.coupon')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_coupons', to='api_hotel.hotel')),
            ],
            options={
                'db_table': 'hotel_coupons',
            },
        ),
    ]
