# Generated by Django 4.1 on 2023-05-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_hotel', '0011_hotelcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='benefit',
            field=models.CharField(blank=True, max_length=1028, null=True),
        ),
    ]
